name: devotion
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_riverpod: ^2.5.1
  cupertino_icons: ^1.0.8
  firebase_core: ^3.1.1
  firebase_storage: ^12.1.0
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  google_sign_in: ^6.2.1
  url_launcher: ^6.1.7
  icons_plus: ^5.0.0
  font_awesome_flutter: ^10.7.0
  file_picker: ^8.1.2
  path_provider: ^2.0.5
  dio: ^5.7.0
  image_picker: ^1.1.2
  pdf: ^3.11.1
  http: ^1.2.2
  audioplayers: ^6.1.0
  just_audio: ^0.9.41
  flutter_launcher_icons: ^0.14.1
  carousel_slider: ^5.0.0
  audiofileplayer: ^2.1.1
  audio_video_progress_bar: ^2.0.3
  rxdart: ^0.27.7
  just_audio_background: ^0.0.1-beta.13
  google_fonts: ^6.2.1
  fpdart: ^1.1.0
  routemaster: ^1.0.1
  open_file_manager: ^1.0.3
  open_file: ^3.5.10
  iconsax_flutter: ^1.0.0
  connectivity_plus: ^6.1.2
  flutter_spinkit: ^5.2.1
  loader_overlay: ^4.0.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/ROF.webp"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
