// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLXVp2HrvY-suq6CWYqgdU6VaQbXG46HY',
    appId: '1:975142255429:web:b3e32a60c741aa528edc2c',
    messagingSenderId: '975142255429',
    projectId: 'reflection-of-faith',
    authDomain: 'reflection-of-faith.firebaseapp.com',
    storageBucket: 'reflection-of-faith.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoTJ6Zw-IFa66bdQiL5aZdDpCSQ4mmLoQ',
    appId: '1:975142255429:android:08429e1627b1354d8edc2c',
    messagingSenderId: '975142255429',
    projectId: 'reflection-of-faith',
    storageBucket: 'reflection-of-faith.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXUwiC8O5vu_WiL7LEhb57Wn_Z_f7VVRs',
    appId: '1:975142255429:ios:bc82bc899e1655698edc2c',
    messagingSenderId: '975142255429',
    projectId: 'reflection-of-faith',
    storageBucket: 'reflection-of-faith.firebasestorage.app',
    androidClientId: '975142255429-15vk4mt5i6551htki32ccq1ofqqo7gl5.apps.googleusercontent.com',
    iosClientId: '975142255429-ut7rvdl9sa5j1thutc3ria6r2cubtf14.apps.googleusercontent.com',
    iosBundleId: 'com.example.devotion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXUwiC8O5vu_WiL7LEhb57Wn_Z_f7VVRs',
    appId: '1:975142255429:ios:bc82bc899e1655698edc2c',
    messagingSenderId: '975142255429',
    projectId: 'reflection-of-faith',
    storageBucket: 'reflection-of-faith.firebasestorage.app',
    androidClientId: '975142255429-15vk4mt5i6551htki32ccq1ofqqo7gl5.apps.googleusercontent.com',
    iosClientId: '975142255429-ut7rvdl9sa5j1thutc3ria6r2cubtf14.apps.googleusercontent.com',
    iosBundleId: 'com.example.devotion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLXVp2HrvY-suq6CWYqgdU6VaQbXG46HY',
    appId: '1:975142255429:web:eb6d2d7f16b054e48edc2c',
    messagingSenderId: '975142255429',
    projectId: 'reflection-of-faith',
    authDomain: 'reflection-of-faith.firebaseapp.com',
    storageBucket: 'reflection-of-faith.firebasestorage.app',
  );

}